# Generated by Django 5.2.16 on 2026-07-15 17:15

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_alter_prescription_options_prescription_added_by_and_more'),
        ('clinics', '0008_clinic_invoice_prefix'),
        ('patients', '0004_patientclinicregistration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeItemDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('service', 'Service'), ('medication', 'Medication'), ('lab_test', 'Lab Test'), ('bed', 'Bed / Room Charge'), ('device', 'Device Usage'), ('other', 'Other')], max_length=16)),
                ('price_components', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_definitions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_definitions', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_definitions', to='clinics.medicine')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('fiscal_year_label', models.CharField(max_length=16)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_counters', to='clinics.clinic')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='active', max_length=16)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='patients.patientprofile')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('line_items_snapshot', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinics.clinic')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patientprofile')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.patientaccount')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='billing.patientaccount')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('service', 'Service'), ('medication', 'Medication'), ('lab_test', 'Lab Test'), ('bed', 'Bed / Room Charge'), ('device', 'Device Usage'), ('other', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='unbilled', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price_components', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('override_reason', models.TextField(blank=True)),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clinics.clinic')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinics.clinicinventoryitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patientprofile')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_charges', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='clinical.prescription')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='clinical.visit')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='billing.chargeitemdefinition')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='billing.invoice')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='billing.patientaccount')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('advance', 'Advance / Deposit'), ('refund', 'Refund / Credit Note')], default='payment', max_length=16)),
                ('tendered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('returned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance')], max_length=16)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.patientaccount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='chargeitemdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', True)), fields=('clinic', 'code', 'version'), name='unique_clinic_code_version'),
        ),
        migrations.AddConstraint(
            model_name='chargeitemdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False)), fields=('clinic', 'doctor', 'code', 'version'), name='unique_clinic_doctor_code_version'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbercounter',
            constraint=models.UniqueConstraint(fields=('clinic', 'fiscal_year_label'), name='unique_clinic_fiscal_year_counter'),
        ),
        migrations.AddConstraint(
            model_name='patientaccount',
            constraint=models.UniqueConstraint(fields=('patient', 'clinic'), name='unique_patient_clinic_account'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('clinic', 'number'), name='unique_clinic_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('account', 'key'), name='unique_account_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='chargeitem',
            index=models.Index(fields=['account', 'status'], name='billing_cha_account_284886_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeitem',
            index=models.Index(fields=['clinic', 'service_date'], name='billing_cha_clinic__69ad99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', 'payment_datetime'], name='billing_pay_account_0fc84f_idx'),
        ),
    ]
