# Generated by Django 5.2.16 on 2026-07-15 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_alter_prescription_options_prescription_added_by_and_more'),
        ('clinics', '0007_clinic_fiscal_year_start_month_clinic_timezone_and_more'),
        ('patients', '0004_patientclinicregistration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('clinic', 'Clinic'), ('lab', 'Lab'), ('test_center', 'Test Center'), ('pharmacy', 'Pharmacy / Medical Store'), ('device', 'Device'), ('other', 'Other')], max_length=16)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('partnered', 'Partnered')], default='owned', max_length=16)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='clinics.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceAccessGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.businessunit')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_grants_given', to=settings.AUTH_USER_MODEL)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_grants_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('source_type', models.CharField(choices=[('clinic_visit', 'Clinic Visit'), ('clinic_procedure', 'In-clinic Procedure / Test'), ('home_visit', 'Home Visit'), ('lab_test', 'Lab Test (own lab)'), ('lab_referral', 'Lab / Test-center Referral Commission'), ('pharmacy_sale', 'Pharmacy Sale (own store)'), ('pharmacy_commission', 'Pharmacy Commission (partnered)'), ('device_income', 'Device Income (sale / rental / per-use)'), ('mr_engagement', 'MR Engagement (honoraria / sponsorship / in-kind)'), ('insurance_claim', 'Insurance Claim'), ('other', 'Other')], max_length=32)),
                ('direction', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('received', 'Received'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('split_enabled', models.BooleanField(default=False)),
                ('doctor_share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='finance.businessunit')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_revenue_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patientprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entry', to='clinical.visit')),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueShareRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('doctor_share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share_rules', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(condition=models.Q(('clinic__isnull', False)), fields=('owner', 'clinic'), name='unique_owner_clinic_business_unit'),
        ),
        migrations.AddIndex(
            model_name='financeaccessgrant',
            index=models.Index(fields=['grantee', 'status'], name='finance_fin_grantee_a225c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('doctor', models.F('grantee')), _negated=True), name='finance_grant_not_self'),
        ),
        migrations.AddConstraint(
            model_name='financeaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('business_unit__isnull', False), ('clinic__isnull', False), _negated=True), name='finance_grant_single_scope'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['doctor', 'occurred_on'], name='finance_rev_doctor__0f157d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['owner', 'occurred_on'], name='finance_rev_owner_i_8d25bc_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['doctor', 'source_type', 'occurred_on'], name='finance_rev_doctor__c51e08_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['clinic', 'occurred_on'], name='finance_rev_clinic__8e3244_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['doctor', 'status'], name='finance_rev_doctor__6c71f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__lte', models.F('amount'))), name='revenue_received_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='revenueentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doctor_share_percentage__isnull', False), ('owner__isnull', False), ('split_enabled', True)), models.Q(('doctor_share_percentage__isnull', True), ('owner__isnull', True), ('split_enabled', False)), _connector='OR'), name='revenue_split_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='revenuesharerule',
            constraint=models.UniqueConstraint(fields=('clinic', 'doctor'), name='unique_clinic_doctor_share_rule'),
        ),
        migrations.AddConstraint(
            model_name='revenuesharerule',
            constraint=models.CheckConstraint(condition=models.Q(('doctor_share_percentage__gte', 0), ('doctor_share_percentage__lte', 100)), name='share_percentage_0_100'),
        ),
    ]
