# Generated by Django 5.2.16 on 2026-07-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("finance", "0003_backfill_historical_visit_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueentry",
            name="charge_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenue_entry",
                to="billing.chargeitem",
            ),
        ),
    ]
