# Generated by Django 5.2.16 on 2026-07-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_remove_clinic_billing_enabled'),
        ('finance', '0004_revenueentry_charge_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entry', to='clinics.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='source_type',
            field=models.CharField(choices=[('clinic_visit', 'Clinic Visit'), ('clinic_procedure', 'In-clinic Procedure / Test'), ('home_visit', 'Home Visit'), ('lab_test', 'Lab Test (own lab)'), ('lab_referral', 'Lab / Test-center Referral Commission'), ('pharmacy_sale', 'Pharmacy Sale (own store)'), ('pharmacy_commission', 'Pharmacy Commission (partnered)'), ('device_income', 'Device Income (sale / rental / per-use)'), ('mr_engagement', 'MR Engagement (honoraria / sponsorship / in-kind)'), ('insurance_claim', 'Insurance Claim'), ('other', 'Other'), ('supply_purchase', 'Supply Purchase')], max_length=32),
        ),
    ]
