# Generated by Django 6.0.7 on 2026-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emergencyaccess'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_9c3bfc_idx',
            old_name='core_audit_user_event_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyaccess',
            new_name='core_emerge_accesse_33e650_idx',
            old_name='core_bg_accessor_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyaccess',
            new_name='core_emerge_patient_3905a5_idx',
            old_name='core_bg_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyaccess',
            new_name='core_emerge_reviewe_c4090c_idx',
            old_name='core_bg_reviewer_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('password_changed', 'Password changed'), ('email_verified', 'Email verified'), ('otp_failed', 'OTP verification failed'), ('account_locked', 'Account locked'), ('token_blacklisted', 'All tokens blacklisted'), ('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('mfa_failed', 'MFA verification failed'), ('mfa_success', 'MFA verification succeeded'), ('break_glass', 'Emergency break-glass access')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='emergencyaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
