# Generated by Django 5.2.16 on 2026-07-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_billing_enabled_and_more'),
        ('core', '0003_rename_core_audit_user_event_idx_core_auditl_user_id_9c3bfc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('entry_created', 'Revenue entry created'), ('entry_updated', 'Revenue entry updated'), ('entry_settled', 'Revenue entry settled'), ('entry_cancelled', 'Revenue entry cancelled'), ('share_rule_created', 'Revenue share rule created'), ('share_rule_updated', 'Revenue share rule updated'), ('grant_created', 'Finance access grant created'), ('grant_revoked', 'Finance access grant revoked'), ('charge_captured', 'Charge item captured'), ('charge_cancelled', 'Charge item cancelled'), ('invoice_issued', 'Invoice issued'), ('invoice_cancelled', 'Invoice cancelled'), ('payment_posted', 'Payment posted'), ('refund_posted', 'Refund posted'), ('advance_posted', 'Advance posted'), ('advance_applied', 'Advance applied to invoice'), ('price_definition_changed', 'Price book definition changed')], db_index=True, max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinics.clinic')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_financ_object__e7d782_idx'), models.Index(fields=['clinic', 'event', 'created_at'], name='core_financ_clinic__2773bb_idx'), models.Index(fields=['actor', 'created_at'], name='core_financ_actor_i_0be096_idx')],
            },
        ),
    ]
