# Generated by Django 5.2.16 on 2026-07-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_purchaseorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftaskgrant',
            name='task_type',
            field=models.CharField(choices=[('manage_staff', 'Manage Staff'), ('manage_inventory', 'Manage Inventory'), ('view_revenue', 'View Revenue'), ('edit_prescriptions', 'Edit Prescriptions'), ('add_vitals', 'Add Vitals'), ('upload_reports', 'Upload Reports'), ('upload_images', 'Upload Images'), ('view_patient_history', 'View Patient History'), ('voice_notes', 'Voice Notes'), ('ocr', 'OCR')], max_length=32),
        ),
    ]
