# Generated by Django 5.2.16 on 2026-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_stafftaskgrant_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialty',
            field=models.CharField(blank=True, choices=[('primary_care', 'Primary Care'), ('family_medicine', 'Family Medicine'), ('cardiology', 'Cardiology'), ('internal_medicine', 'Internal Medicine'), ('pediatrics', 'Pediatrics'), ('urgent_care', 'Urgent Care'), ('other', 'Other')], max_length=32),
        ),
    ]
