# Generated by Django 5.2.16 on 2026-07-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0004_clinic_hours_clinic_notes_clinic_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_medicines', to=settings.AUTH_USER_MODEL),
        ),
    ]
