# Generated by Django 5.2.16 on 2026-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_medicine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='billing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stafftaskgrant',
            name='task_type',
            field=models.CharField(choices=[('manage_staff', 'Manage Staff'), ('manage_inventory', 'Manage Inventory'), ('view_revenue', 'View Revenue'), ('edit_prescriptions', 'Edit Prescriptions'), ('add_vitals', 'Add Vitals'), ('upload_reports', 'Upload Reports'), ('upload_images', 'Upload Images'), ('view_patient_history', 'View Patient History'), ('voice_notes', 'Voice Notes'), ('ocr', 'OCR'), ('manage_billing', 'Manage Billing'), ('manage_refunds', 'Manage Refunds')], max_length=32),
        ),
    ]
