# Generated by Django 5.2.16 on 2026-07-15 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_billing_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='clinic',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_year_start_month__gte', 1), ('fiscal_year_start_month__lte', 12)), name='fiscal_year_start_month_valid'),
        ),
    ]
