# Generated by Django 5.2.16 on 2026-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_fiscal_year_start_month_clinic_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
