# Generated by Django 5.2.16 on 2026-07-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_invoice_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='billing_enabled',
        ),
    ]
