"""
Doctor income attribution — "what did this doctor earn, from where".

This app never imports apps.billing at module level — the bridge
(apps.finance.services.record_billing_payment, called by apps.billing.services
via a function-local import) is the only thing that touches ChargeItem,
and only ever by primary key / FK assignment, never a model import.
"""

from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils import timezone

from apps.core.models import BaseModel
from apps.core.money import DEFAULT_CURRENCY, PaymentMode, quantize2

# ---------------------------------------------------------------------------
# BusinessUnit — what earned the money
# ---------------------------------------------------------------------------


class BusinessUnitType(models.TextChoices):
    CLINIC = "clinic", "Clinic"
    LAB = "lab", "Lab"
    TEST_CENTER = "test_center", "Test Center"
    PHARMACY = "pharmacy", "Pharmacy / Medical Store"
    DEVICE = "device", "Device"
    OTHER = "other", "Other"


class BusinessOwnership(models.TextChoices):
    OWNED = "owned", "Owned"
    PARTNERED = "partnered", "Partnered"


class BusinessUnit(BaseModel):
    """
    One income source in a doctor's practice — a clinic, lab, pharmacy,
    test center, device, or partnership. `RevenueEntry` rows attribute
    income to one of these (or to none, for personal income like home
    visits and MR honoraria that don't belong to a facility).

    A platform `Clinic` gets a matching unit auto-created on registration
    (see apps.clinics.views.ClinicViewSet.perform_create) and via a
    backfill migration for clinics that existed before this app did.
    """

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="business_units"
    )
    name = models.CharField(max_length=255)
    unit_type = models.CharField(max_length=16, choices=BusinessUnitType.choices)
    ownership = models.CharField(
        max_length=16, choices=BusinessOwnership.choices, default=BusinessOwnership.OWNED
    )
    # Set when unit_type=CLINIC and the clinic is platform-managed. One
    # BusinessUnit per (owner, clinic) — enforced below.
    clinic = models.ForeignKey(
        "clinics.Clinic",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="business_units",
    )
    # For PARTNERED units: the agreed commission percentage. Informational
    # only in Phase 1 — no auto-computation; the doctor records the
    # commission amount they actually received as a manual RevenueEntry.
    commission_rate = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    contact_name = models.CharField(max_length=255, blank=True)
    contact_phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=500, blank=True)
    notes = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    class Meta(BaseModel.Meta):
        # Must subclass BaseModel.Meta — a bare `class Meta:` on a concrete
        # model silently drops the abstract base's `ordering` rather than
        # inheriting it (see apps.clinics.models.Clinic for the same note).
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "clinic"],
                condition=models.Q(clinic__isnull=False),
                name="unique_owner_clinic_business_unit",
            )
        ]

    def __str__(self):
        return f"BusinessUnit<{self.owner_id}:{self.name}>"


# ---------------------------------------------------------------------------
# RevenueShareRule — who gets what percentage
# ---------------------------------------------------------------------------


class RevenueShareRule(BaseModel):
    """
    Per-doctor-per-clinic revenue split configuration, managed by the
    clinic OWNER only. When
    `enabled`, every new revenue entry generated by `doctor`'s work at
    `clinic` is split: the doctor's dashboard counts
    `doctor_share_percentage`% of the amount, the owner's dashboard
    counts the remainder. Applied as a SNAPSHOT at entry-capture time
    (see RevenueEntry.split_enabled/doctor_share_percentage) — editing or
    disabling a rule affects future entries only, never history.

    No rule (or `enabled=False`) means no split at all: the conducting
    doctor is credited the entire amount.
    """

    clinic = models.ForeignKey(
        "clinics.Clinic", on_delete=models.CASCADE, related_name="revenue_share_rules"
    )
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="revenue_share_rules"
    )
    enabled = models.BooleanField(default=True)  # the "percentage boolean flag"
    doctor_share_percentage = models.DecimalField(max_digits=5, decimal_places=2)  # 0-100
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    notes = models.TextField(blank=True)  # e.g. "60/40 as agreed July 2026"

    class Meta(BaseModel.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=["clinic", "doctor"], name="unique_clinic_doctor_share_rule"
            ),
            models.CheckConstraint(
                check=models.Q(doctor_share_percentage__gte=0, doctor_share_percentage__lte=100),
                name="share_percentage_0_100",
            ),
        ]

    def __str__(self):
        return (
            f"RevenueShareRule<{self.clinic_id}:{self.doctor_id}={self.doctor_share_percentage}%>"
        )


# ---------------------------------------------------------------------------
# RevenueEntry — the ledger row
# ---------------------------------------------------------------------------


class RevenueSource(models.TextChoices):
    """
    Closed vocabulary of income origins — same rationale as
    apps.clinics.models.PermissionFlag and apps.patients.models.ConsentScope:
    a typo'd or invented category can't silently vanish from (or fabricate)
    dashboard aggregates.
    """

    CLINIC_VISIT = "clinic_visit", "Clinic Visit"
    CLINIC_PROCEDURE = "clinic_procedure", "In-clinic Procedure / Test"
    HOME_VISIT = "home_visit", "Home Visit"
    LAB_TEST = "lab_test", "Lab Test (own lab)"
    LAB_REFERRAL = "lab_referral", "Lab / Test-center Referral Commission"
    PHARMACY_SALE = "pharmacy_sale", "Pharmacy Sale (own store)"
    PHARMACY_COMMISSION = "pharmacy_commission", "Pharmacy Commission (partnered)"
    DEVICE_INCOME = "device_income", "Device Income (sale / rental / per-use)"
    MR_ENGAGEMENT = "mr_engagement", "MR Engagement (honoraria / sponsorship / in-kind)"
    INSURANCE_CLAIM = "insurance_claim", "Insurance Claim"
    OTHER = "other", "Other"
    SUPPLY_PURCHASE = "supply_purchase", "Supply Purchase"  # EXPENSE direction only


class EntryDirection(models.TextChoices):
    INCOME = "income", "Income"
    EXPENSE = "expense", "Expense"  # PurchaseOrder-derived supply costs


class EntryStatus(models.TextChoices):
    """
    DERIVED from (amount, amount_received) — recomputed by
    apps.finance.services on every save; never trusted from a client
    except the two terminal states, which are only ever set explicitly.
    """

    PENDING = "pending", "Pending"  # amount_received == 0
    PARTIAL = "partial", "Partially Received"  # 0 < amount_received < amount
    RECEIVED = "received", "Received"  # amount_received == amount
    REFUNDED = "refunded", "Refunded"  # terminal, set explicitly
    CANCELLED = "cancelled", "Cancelled"  # terminal, set explicitly


class RevenueEntry(BaseModel):
    """
    One money event in a doctor's practice — the single source of truth
    the finance dashboard aggregates over. Written by the billing bridge
    (visit quick-pay, manual charges/invoices/payments — see
    `record_billing_payment`) or a manual entry the doctor records
    directly. Historical rows linked via `visit` predate the retirement
    of the finance-only visit-capture path and are never written fresh
    anymore, but remain valid history.

    A single row can have up to two beneficiaries (revenue sharing):
    `doctor` (the conducting/recording doctor) and `owner` (the clinic
    owner receiving the remainder when a split is enabled). Each viewer's
    dashboard aggregates only their own slice — see `doctor_share_amount`
    / `owner_share_amount`.
    """

    # Conducting/recording doctor — for auto visit entries this is
    # visit.doctor; for manual entries, the doctor who recorded it.
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="revenue_entries"
    )
    # Set ONLY when a revenue split applies (RevenueShareRule enabled for
    # this clinic/doctor pair): the clinic owner who receives the
    # remainder. Null on every unsplit entry (the common solo-practice case).
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="owned_revenue_entries",
    )
    business_unit = models.ForeignKey(
        BusinessUnit,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="revenue_entries",
    )
    # DERIVED, never independently writable: resolved via
    # apps.finance.services.resolve_entry_attribution
    # from business_unit.clinic / visit.clinic at the single write choke
    # point; a mismatching explicit value is a validation error. Kept as a
    # direct FK (not reached via business_unit.clinic) so clinic
    # attribution survives unit soft-deletion, and clinic-scoped access
    # grants filter without traversing another doctor's unit.
    clinic = models.ForeignKey(
        "clinics.Clinic",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="revenue_entries",
    )
    source_type = models.CharField(max_length=32, choices=RevenueSource.choices)
    direction = models.CharField(
        max_length=8, choices=EntryDirection.choices, default=EntryDirection.INCOME
    )
    amount = models.DecimalField(max_digits=12, decimal_places=2)  # total billed/earned
    amount_received = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    # Global-readiness seam — stamped from the clinic's currency
    # at creation (DEFAULT_CURRENCY today, everywhere); never independently
    # writable, same derivation discipline as `clinic` above.
    currency = models.CharField(max_length=3, default=DEFAULT_CURRENCY)
    payment_mode = models.CharField(max_length=16, choices=PaymentMode.choices, blank=True)
    status = models.CharField(
        max_length=16, choices=EntryStatus.choices, default=EntryStatus.PENDING
    )
    # Default is a same-process fallback for manual entries with no
    # attributable clinic; every AUTO capture path explicitly passes
    # occurred_on (visit.visit_date), never the bare field default.
    occurred_on = models.DateField(default=timezone.localdate, db_index=True)
    settled_on = models.DateField(null=True, blank=True)  # stamped when fully received
    # Split snapshot (from RevenueShareRule at capture time) — later rule
    # edits never rewrite history.
    split_enabled = models.BooleanField(default=False)
    doctor_share_percentage = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True
    )
    # Source links — explicit FK per source (house style; never a
    # GenericForeignKey).
    visit = models.OneToOneField(
        "clinical.Visit",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="revenue_entry",
    )
    # Set by the billing bridge (apps.finance.services.record_billing_payment)
    # once a clinic's charge items start flowing through apps.billing —
    # never written by anything else. Idempotent upsert key: one bridged
    # entry per charge item, refreshed (not recreated) on re-issue after a
    # cancellation.
    charge_item = models.OneToOneField(
        "billing.ChargeItem",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="revenue_entry",
    )
    # Written once by apps.clinics.views.PurchaseOrderReceiveView via
    # apps.finance.services.record_purchase_expense — an EXPENSE-direction
    # entry, never split (expenses are owner-level; see get_active_share_rule
    # only ever being called for income entries).
    purchase_order = models.OneToOneField(
        "clinics.PurchaseOrder",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="revenue_entry",
    )
    patient = models.ForeignKey(
        "patients.PatientProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    recorded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    notes = models.TextField(blank=True)
    # Free-form extras per source — e.g. MR in-kind items:
    # {"mr_company": "...", "items": [{"kind": "samples", "description":
    # "...", "estimated_value": "1500.00"}, ...]}. estimated_value is
    # informational only and never summed into money totals.
    metadata = models.JSONField(default=dict, blank=True)

    class Meta(BaseModel.Meta):
        indexes = [
            models.Index(fields=["doctor", "occurred_on"]),
            models.Index(fields=["owner", "occurred_on"]),
            models.Index(fields=["doctor", "source_type", "occurred_on"]),
            models.Index(fields=["clinic", "occurred_on"]),
            models.Index(fields=["doctor", "status"]),
        ]
        constraints = [
            models.CheckConstraint(
                check=models.Q(amount_received__lte=models.F("amount")),
                name="revenue_received_lte_amount",
            ),
            # Split fields travel together — either all three are set
            # (a real split) or none are (the unsplit default).
            models.CheckConstraint(
                check=(
                    models.Q(
                        split_enabled=True,
                        doctor_share_percentage__isnull=False,
                        owner__isnull=False,
                    )
                    | models.Q(
                        split_enabled=False,
                        doctor_share_percentage__isnull=True,
                        owner__isnull=True,
                    )
                ),
                name="revenue_split_fields_consistent",
            ),
        ]

    def __str__(self):
        return f"RevenueEntry<{self.doctor_id}:{self.source_type}:{self.amount}>"

    @property
    def doctor_share_amount(self) -> Decimal:
        """What the conducting doctor's dashboard counts for this entry."""
        if not self.split_enabled:
            return self.amount
        return quantize2(self.amount * self.doctor_share_percentage / Decimal("100"))

    @property
    def owner_share_amount(self) -> Decimal:
        """
        What the clinic owner's dashboard counts (0 when unsplit).
        Computed as the remainder — never independently rounded — so
        doctor_share_amount + owner_share_amount always equals `amount`
        exactly, to the paisa.
        """
        if not self.split_enabled:
            return Decimal("0")
        return self.amount - self.doctor_share_amount


# ---------------------------------------------------------------------------
# FinanceAccessGrant — doctor-controlled visibility
# ---------------------------------------------------------------------------


class FinanceGrantStatus(models.TextChoices):
    ACTIVE = "active", "Active"
    REVOKED = "revoked", "Revoked"
    EXPIRED = "expired", "Expired"


class FinanceAccessGrant(BaseModel):
    """
    A doctor granting another platform user read access to their finance
    data. View-only — no grant tier allows creating/editing entries on
    the doctor's behalf. Mirrors the apps.patients.ConsentGrant /
    apps.clinics.StaffTaskGrant lifecycle pattern already in the codebase.
    """

    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="finance_grants_given"
    )
    grantee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="finance_grants_received",
    )
    # Optional scope narrowing — both null = the doctor's ENTIRE finance
    # picture. Set one to limit the grantee to a single clinic's or a
    # single business unit's slice.
    clinic = models.ForeignKey(
        "clinics.Clinic", on_delete=models.CASCADE, null=True, blank=True, related_name="+"
    )
    business_unit = models.ForeignKey(
        BusinessUnit, on_delete=models.CASCADE, null=True, blank=True, related_name="+"
    )
    status = models.CharField(
        max_length=16, choices=FinanceGrantStatus.choices, default=FinanceGrantStatus.ACTIVE
    )
    expires_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)

    class Meta(BaseModel.Meta):
        constraints = [
            models.CheckConstraint(
                check=~models.Q(doctor=models.F("grantee")), name="finance_grant_not_self"
            ),
            # At most one scope narrowing.
            models.CheckConstraint(
                check=~models.Q(clinic__isnull=False, business_unit__isnull=False),
                name="finance_grant_single_scope",
            ),
        ]
        indexes = [models.Index(fields=["grantee", "status"])]

    def __str__(self):
        return f"FinanceAccessGrant<{self.doctor_id}->{self.grantee_id}:{self.status}>"
