# Generated by Django 6.0.7 on 2026-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_totp_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='users_passw_user_id_053982_idx',
            old_name='users_pwdhist_user_idx',
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
