# Generated by Django 5.2.16 on 2026-07-11 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientMergeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merged_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_source', to='patients.patientprofile')),
                ('primary_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_absorbed', to='patients.patientprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('grantee_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_grants', to='clinics.clinic')),
                ('grantee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_grants_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_grants', to='patients.patientprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'status'], name='patients_co_patient_1e8f95_idx'), models.Index(fields=['grantee_user', 'status'], name='patients_co_grantee_37614f_idx'), models.Index(fields=['grantee_clinic', 'status'], name='patients_co_grantee_7e96d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('grantee_clinic__isnull', False), ('grantee_user__isnull', True)), models.Q(('grantee_clinic__isnull', True), ('grantee_user__isnull', False)), _connector='OR'), name='consent_grant_exactly_one_grantee')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patientprofile')),
                ('related_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patientprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'related_patient'), name='unique_family_member_link'), models.CheckConstraint(condition=models.Q(('patient', models.F('related_patient')), _negated=True), name='family_member_not_self')],
            },
        ),
        migrations.CreateModel(
            name='PatientClinicRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('mrn', models.CharField(blank=True, max_length=32)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_registrations', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_registrations', to='patients.patientprofile')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'clinic'), name='unique_patient_clinic_registration')],
            },
        ),
    ]
