# Generated by Django 5.2.16 on 2026-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_claimed_at_patientprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinicregistration',
            name='status',
            field=models.CharField(choices=[('stable', 'Stable'), ('monitoring', 'Monitoring'), ('critical', 'Critical'), ('discharged', 'Discharged'), ('scheduled', 'Scheduled')], default='stable', max_length=16),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=8),
        ),
    ]
