"""
Shared money vocabulary and helpers for apps.billing and apps.finance.

Lives in apps.core (not either money app) so neither app depends on the
other for a plain enum — the layering rule is that apps.billing and
apps.finance must never import each other at module
level.

`PaymentMode` originally lived on apps.clinical.models; it moved here since
both new apps need it and depending on apps.clinical for a payment-method
enum would be an odd layering (clinical is a downstream consumer of money,
not its source). The move is DB-invisible: Django serializes `choices=`
as a literal list of tuples into migrations, not a reference to the
TextChoices class, so no migration is generated by this move. See
apps.clinical.models for the re-export kept for import-site compatibility.
"""

from datetime import date
from decimal import ROUND_HALF_UP, Decimal
from zoneinfo import ZoneInfo

from django.db import models
from django.utils import timezone as django_timezone

# Two-decimal-place precision for all money fields — every model in
# apps.billing/apps.finance uses DecimalField(max_digits=12, decimal_places=2).
TWO_PLACES = Decimal("0.01")

# The platform is India-only today — every Clinic.currency/User-facing
# amount is INR. A constant (rather than a bare "INR" literal scattered
# across model defaults) so the single-currency assumption is greppable
# and has exactly one place to change when a second currency exists.
DEFAULT_CURRENCY = "INR"


class PaymentMode(models.TextChoices):
    CASH = "cash", "Cash"
    CARD = "card", "Card"
    UPI = "upi", "UPI"
    INSURANCE = "insurance", "Insurance"


def clinic_localdate(clinic) -> date:
    """
    The current date in `clinic`'s own configured timezone
    (Clinic.timezone), not the process-wide TIME_ZONE setting.

    Every clinic-scoped, money-critical date — RevenueEntry.occurred_on,
    ChargeItem.service_date, billing day-book boundaries, invoice
    fiscal-year computation — must be derived from this, never from
    django.utils.timezone.localdate(). The platform is India-only today
    (every Clinic.timezone == "Asia/Kolkata", matching the process-wide
    TIME_ZONE default), so the two currently agree everywhere — but this
    is the seam that keeps a future non-Indian clinic's money correctly
    dated without revisiting any of this code again. See
    """
    return django_timezone.now().astimezone(ZoneInfo(clinic.timezone)).date()


def quantize2(value: Decimal) -> Decimal:
    """
    Round `value` to 2 decimal places, half-up (the everyday rounding rule
    for currency, as opposed to Python/Decimal's default banker's rounding).

    Used at every money computation boundary — price components, revenue
    share splits, payment allocations — so a total is always the sum of
    already-quantized parts rather than a re-derived, potentially
    differently-rounded number.
    """
    return value.quantize(TWO_PLACES, rounding=ROUND_HALF_UP)
