# Generated by Django 6.0.7 on 2026-07-08 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
    ]
