# Generated by Django 5.2.16 on 2026-07-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='preferred_medicines',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_doctors', to='clinics.medicine'),
        ),
    ]
