# Generated by Django 5.2.16 on 2026-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_preferred_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='credentials',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='licensed_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
